version: '3.8'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - laravel_vendor:/var/www/vendor
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - angular_node_modules:/app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start -- --host=0.0.0.0"
    stdin_open: true
    tty: true
    depends_on:
      - laravel

volumes:
  angular_node_modules:
  laravel_vendor:
